---
provisioner:
  name: chef_solo
  data_bags_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret

suites:
  - name: client
    run_list:
      - recipe[rdiff-backup::client]
  - name: server
    run_list:
      - recipe[rdiff-backup-test::create_server]
      - recipe[rdiff-backup-test::delete_server]
