---
driver_config:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
  key_name: <%= ENV['OS_SSH_KEYPAIR'] %>
  private_key_path: <%= ENV['OS_PRIVATE_SSH_KEY'] %>
  public_key_path: <%= ENV['OS_PUBLIC_SSH_KEY'] %>
  openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
  floating_ip: <%= ENV['OS_FLOATING_IP'] %>
  floating_ip_pool: <%= ENV['OS_FLOATING_IP_POOL'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_REF'] %>

provisioner:
  name: chef_zero
  roles_path: test/integration/roles
  data_bags_path: test/integration/data_bags
  attributes:
    authorization:
      sudo:
        users:
          - centos
          - ubuntu
          - fedora
          - debian
        passwordless: true

platforms:
- name: centos-6.6
  driver_plugin: openstack
  driver_config:
    username: centos
    image_ref: "CentOS 6.6"
- name: centos-7.0
  driver_plugin: openstack
  driver_config:
    username: centos
    image_ref: "CentOS 7.0"

suites:
  - name: client
    run_list:
      - role[client]
  - name: server
    run_list:
      - role[server]
  - name: all
    run_list:
      - role[client]
      - role[server]
