AllCops:
  Include:
    - '**/Berksfile'
    - '**/Cheffile'
  Exclude:
    - '**/metadata.rb'
    - 'cookbooks/**/*'
Documentation:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only
Metrics/LineLength:
  Max: 120

Style/IfUnlessModifier:
  MaxLineLength: 120

Style/WhileUntilModifier:
  MaxLineLength: 120
