name             'rdiff-backup'
maintainer       'Oregon State University'
maintainer_email 'systems@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures rdiff-backup'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '2.0.10'
issues_url       'https://github.com/osuosl-cookbooks/rdiff-backup/issues'
source_url       'https://github.com/osuosl-cookbooks/rdiff-backup'

depends 'ssh-keys'
depends 'ssh_user'
depends 'yum'
depends 'yum-epel'
depends 'user'
depends 'partial_search'
depends 'sudo', '< 3.0.0'
depends 'nagios', '< 8.0.0'
depends 'nrpe'

supports 'centos', '~> 6.0'
supports 'centos', '~> 7.0'
