#!/bin/bash

read -d ' ' -a JOBS <<< "`ls /home/rdiff-backup-server/scripts`" # Array of all jobs

# Backup jobs
TOTAL=${#JOBS[@]}
SUCC=0
NORMFAIL=0
FIRSTFAIL=0
MISSING=0

# Purges
PTOTAL=${#JOBS[@]}
PSUCC=0
PFAIL=0
PMISSING=0

LOGS=`ls /var/log/rdiff-backup/general/* | tail -n 2 | xargs` # Last 2 logs

for JOB in ${JOBS[@]}; do

  # Backup jobs
  JOBSTATUS=`grep $JOB $LOGS | grep -Ei 'backup (complete|failed)' | tail -n 1`
  if [ `echo $JOBSTATUS | grep -q 'Backup complete'; echo $?` -eq 0 ]; then
    SUCC=`expr $SUCC + 1`;
  elif [ `echo $JOBSTATUS | grep -q 'Backup failed'; echo $?` -eq 0 ]; then
    NORMFAILJOBS[$NORMFAIL]=$JOB
    NORMFAIL=`expr $NORMFAIL + 1`;
  elif [ `echo $JOBSTATUS | grep -q 'First backup failed'; echo $?` -eq 0 ]; then
    FIRSTFAILJOBS[$FIRSTFAIL]=$JOB
    FIRSTFAIL=`expr $FIRSTFAIL + 1`;
  else
    MISSINGJOBS[$MISSING]=$JOB
    MISSING=`expr $MISSING + 1`;
  fi

  # Purges
  JOBSTATUS=`grep $JOB $LOGS | grep -Ei 'purge (complete|failed)' | tail -n 1`
  if [ `echo $JOBSTATUS | grep -q 'Purge complete'; echo $?` -eq 0 ]; then
    PSUCC=`expr $PSUCC + 1`;
  elif [ `echo $JOBSTATUS | grep -q 'Purge failed'; echo $?` -eq 0 ]; then
    PFAILJOBS[$PFAIL]=$JOB
    PFAIL=`expr $PFAIL + 1`;
  else
    PMISSINGJOBS[$PMISSING]=$JOB
    PMISSING=`expr $PMISSING + 1`;
  fi
done

STATUS="UNKNOWN:"
MESSAGE="$SUCC/$TOTAL backup(s) succeeded"
if [ $TOTAL -eq $SUCC -a $PTOTAL -eq $PSUCC ]; then
  STATUS="OK:"
fi

# Backup jobs
if [ $MISSING -ne 0 ]; then
  STATUS="WARNING:"
  MESSAGE="${MESSAGE}; $MISSING backup(s) are missing ( "
  for MISSINGJOB in ${MISSINGJOBS[@]}; do
    MESSAGE="${MESSAGE}${MISSINGJOB} "
  done
  MESSAGE="${MESSAGE})"
fi
if [ $NORMFAIL -ne 0 ]; then
  STATUS="OK:"
  MESSAGE="${MESSAGE}; $NORMFAIL existing backup(s) failed ( "
  for NORMFAILJOB in ${NORMFAILJOBS[@]}; do
    MESSAGE="${MESSAGE}${NORMFAILJOB} "
  done
  MESSAGE="${MESSAGE})"
fi
if [ $FIRSTFAIL -ne 0 ]; then
  STATUS="CRITICAL:"
  MESSAGE="${MESSAGE}; $FIRSTFAIL first backup(s) failed ( "
  for FIRSTFAILJOB in ${FIRSTFAILJOBS[@]}; do
    MESSAGE="${MESSAGE}${FIRSTFAILJOB} "
  done
  MESSAGE="${MESSAGE})"
fi

# Purges
if [ $PMISSING -ne 0 ]; then
  STATUS="WARNING:"
  MESSAGE="${MESSAGE}; $PMISSING purge(s) are missing ( "
  for PMISSINGJOB in ${PMISSINGJOBS[@]}; do
    MESSAGE="${MESSAGE}${PMISSINGJOB} "
  done
  MESSAGE="${MESSAGE})"
fi
if [ $PFAIL -ne 0 ]; then
  STATUS="CRITICAL:"
  MESSAGE="${MESSAGE}; $PFAIL purge(s) failed ( "
  for PFAILJOB in ${PFAILJOBS[@]}; do
    MESSAGE="${MESSAGE}${PFAILJOB} "
  done
  MESSAGE="${MESSAGE})"
fi

echo "$STATUS $MESSAGE"
if [ $STATUS = "OK:" ]; then
  exit 0
elif [ $STATUS = "WARNING:" ]; then
  exit 1
else
  exit 2
fi
